### PR TITLE
Feat/cp 70 add codegen and typescript plugin

### PR DESCRIPTION
**Pull request by 99032000**
1. setup codegen, add dependency and config.
2. update package json.
3. disable image optimization due to static export.

### CODE REVIEW

**Review by NorrisWu0 — DISMISSED** [review]
lgtm

**Review by Chris-Wang — CHANGES_REQUESTED** [review]
1. After run `yarn generate`, it will auto generate and reformat files which does not align our prettier config, and failed format check:
image
2. Please squash your commits into one, and following our commits standard like:

```
feat: add codegen and typescript plugin

Setup codegen and added dependency and config;
updated package json;
disabled image optimization due to static export.

Resolve CP-70
```

**Comment by 99032000** [comment]
1. The format issue is fixed.
2. git commits have been squashed.  
@Chris-Wang

**Review by Chris-Wang — APPROVED** [review]
lgtm

**Pull request merged**
